// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:2bbdd82f-8015-4baf-8a76-0f2fe10e0cf8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_8RfgLVRM0",
    "aws_user_pools_web_client_id": "jhj7edasirqk9v1s596uhfuet",
    "aws_appsync_graphqlEndpoint": "https://g6umxhykhfbcvnrarfuxbbvexi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "blu-20181211105758-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://blu-20181211105758-hostingbucket.s3-website.us-east-2.amazonaws.com",
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "moods",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
